[pytest]
testpaths = tests
pythonpath = .
addopts = -q
filterwarnings =
    ignore:You are using a non-supported Python version:FutureWarning
    ignore:You are using a Python version 3.9 past its end of life:FutureWarning
    ignore:urllib3 v2 only supports OpenSSL:Warning
